### ISSUE TITLE
#2 - Design the page banner with title and sub-title

### ISSUE THREAD

**Issue by kepop1** [surajverma2587/project-tracker#2]
### Tasks
- [x] Banner should have a title "Project Expense Tracker"
- [x] Banner should have a sub-title "A world-class app that helps you track your project expenses"
- [x] Banner should be styled using bootstrap classes
- [x] Banner should not include clock
