### ISSUE TITLE
#3 - Add a system clock on the banner

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/project-tracker#3]
### Tasks
- [x] Banner should include the system clock 
- [x] The format of the clock should be "March of 26th, 2021 15:00:03"
- [ ] The clock should tick for every 1 second
