### ISSUE TITLE
#4 - Add styled table to display the projects

### ISSUE THREAD

**Issue by surajverma2587** [surajverma2587/project-tracker#6]
### Tasks
- [x] Table should contain Project Name | Project Type | Hourly Rate ($) | Due Date | Days Until Due Date | Potential Total Earnings ($) | Empty column for delete button
- [ ] Table to contain some mock data for now that comes from javascript
- [ ] Delete button should do nothing for now
